- name: Lab Work Task. Tomcat AS Provisioning
  hosts: tomcat
  remote_user: vagrant
  become: True
  become_method: sudo

  vars:
    java_version: 1.8.0
    tomcat_version: 8
    tomcat_subversion: 0.45
    tomcat_url: http://localhost:8080/

  pre_tasks:
  - debug: msg="Now let the story begin"

  tasks:

  - name: Installing the latest version of Java...
    yum:
      name: java-{{java_version}}-openjdk-devel.x86_64
      state: latest

  - name: Is the tomcat's group exists?
    group:
      name: tomcat_as_group
      state: present
      
  - name: Is the tomcat's user exists?
    user:
      name: tomcat_as
      group: tomcat_as_group
      home: /opt/tomcat/
      state: present

  - name: Creating the CATALINA_HOME folder...
    file:
      path: /opt/tomcat/{{tomcat_version}}.{{tomcat_subversion}}/
      state: directory
      recurse: yes
      mode: 0775

  - name: Downloading Tomcat server...
    get_url:
      url:  http://archive.apache.org/dist/tomcat/tomcat-{{tomcat_version}}/v{{tomcat_version}}.{{tomcat_subversion}}/bin/apache-tomcat-{{tomcat_version}}.{{tomcat_subversion}}.tar.gz 
      dest: /home/vagrant/

  - name: Unarchiving...
    unarchive:
      src:  /home/vagrant/apache-tomcat-{{tomcat_version}}.{{tomcat_subversion}}.tar.gz 
      dest: /home/vagrant/
      remote_src: yes

  - name: Copy tomcat to /opt/tomcat/$version
    shell: cp -R /home/vagrant/apache-tomcat-{{tomcat_version}}.{{tomcat_subversion}}/* /opt/tomcat/{{tomcat_version}}.{{tomcat_subversion}} && chown -R tomcat_as:tomcat_as_group /opt/tomcat/
  
  - name: Creating tomcat.service file
    get_url:
      url: https://raw.githubusercontent.com/PaulYurchuk/stuff/master/tomcat.service
      dest: /home/vagrant

  - name: Copy tomcat.service file
    copy:
      src: /home/vagrant/tomcat.service
      dest: /etc/systemd/system
      remote_src: true
    become: true
    become_method: sudo

  - name: Daemon reload 
    shell: systemctl daemon-reload

  - name: Starting Tomcat server
    service: 
      name: tomcat
      state: started 
      enabled: yes

  - name: Checking tomcat service available by "shell" comand
    shell: ps -ef | grep tomcat
    register: output
  - debug: var=output
    
  - name: Checking tomcat service available by "shell" comand 
    shell: curl -IS {{tomcat_url}}
    register: output
  - debug: var=output

  - name: Checking tomcat service available by "shell" comand 
    shell: systemctl status -l tomcat | grep active
    register: output
  - debug: var=output
    
  - name: Checking tomcat service available by "uri" module
    uri:
      status_code: 200
      url: http://localhost:8080
      return_content: yes
    register: webpage

  - name: Tomcat is unavailable     
    fail:
      msg: 'Tomcat is not available wow'     
    when: "'Tomcat' not in webpage.content"